### ISSUE TITLE
README edits

### ISSUE THREAD

**Issue by lukenoaa** [baydenwillms/TermMatchAI#1]
* In introduction, suggest changing "eDNA repositories such as DarwinCore and MIMARKS MIXs" to "biological data standards including Darwin Core and MIxS". (MIxS is the general case of MIMARKS.)

**Comment by lukenoaa** [comment]
This is a comment on the instructions and the code also. I was trying to follow the instructions to provide my own values for dataset1_terms and dataset2_terms, but it's not clear where these inputs go. Are they entered on the command line? Am I supposed to modify data_loading.py? Looking at that file, it does contain the terms that are used by default (in noaa_terms_w_data and GEOME_terms_w_data), but it doesn't mention dataset1_terms and dataset2_terms.

I think a good way to implement the code would be to allow the user to provide 2 CSV files as input (arguments to the python script) that are formatted to be turned into dicts. You could provide the example data as example CSV files.

Finally, I think it would be important to allow the code to handle lots of examples (either additional input files, or an input file that is a composite of lots of values for each field -- the latter is probably simpler to implement). There is only so much the AI model can learn from a field name and a single example. Having lot of examples for each field would allow it to learn better what a user puts in each field.

Ultimately, there will never be a perfect match for every term, because there is not a one-to-one relationship between terms. Some relationships will be many-to-one, one-to-many, or contain information that is not captured by the other set of terms at all.

**Comment by baydenwillms** [comment]
Hi Luke, thank you for all of the feedback! I will make all the changes to the README, as well as over-haul it to make sure it has all the necessary instructions.  

To answer your question about data_loading.py and how data is given to this program- it's not apparent from this repository, but the code for creating the dictionaries is actually in the noaa-omics-templates repository (where I was working with Google Sheets a few months ago).  It can take either a Google Sheet OR an Excel file, and if you tell it what row the column names are on, it will create dictionaries accordingly for each dataset. It also optionally allows you to take example data and attach it to each data term, as key:value pairs (although it does this sort of naively, it takes the first non-blank Cell's contents as the example data for that column/term) . I will add all the data input code into this (TermMatchAI) project. I can also implement that same code but from CSV files, too.  

And yes, having lots of examples for each field would certainly help the model get better results (and wouldn't be too difficult to implement, because the inputs to the AI model are tokenized). To prevent bulkiness / a slow runtime, I'm intrigued by the possibility of having each user train the model with an input file like you mentioned: "an input file that is a composite of lots of values for each field". The code I currently have for creating the dictionaries is already pretty close to automatically creating an input file like you mentioned.

**Comment by baydenwillms** [comment]
Closing this for now, I did not yet implement the improved input structure with more examples, like you mentioned, but I added information to the README and code files on how to build the input dictionaries from Excel, Google Sheets, (and eventually) CSV and probably TSV
